name: Deploy develop
on:
  push:
    branches:
      - main
jobs:
  bumping:
    name: Bumping version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: git config user.name "${GITHUB_ACTOR}"
      - run: git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm i
      - name: Bumping
        run: npm run minor
      - run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
